// Generated by /openbims_video record {{MODULE}}.
// Do not edit by hand — re-run `record` to regenerate from mockplay/*.md.
//
// One Playwright test that walks every submodule in playback order.
// `markBeat` emits stdout markers consumed by parse-timing.mjs.

import { test, expect } from '@playwright/test';
import {
  installHighlights, focusOn, clearFocus, moveAndClick,
  smoothScroll, typeSlow, beat, markBeat,
} from '../../templates/_helpers.js';

test.describe.configure({ mode: 'serial' });

test('{{MODULE}} — narrative tour', async ({ page }) => {
  test.setTimeout(10 * 60 * 1000);

  // Forward [BEAT] console emissions to Playwright stdout (record.log)
  // so parse-timing.mjs can build clips/timing.json.
  page.on('console', (msg) => {
    const t = msg.text();
    if (t.startsWith('[BEAT]')) console.log(t);
  });

  // Boot at the first route.
  await page.goto('{{FIRST_ROUTE}}', { waitUntil: 'networkidle' });
  await installHighlights(page);
  await markBeat(page, 'video-start', '');
  await beat(page, 1000);

  // ── Submodule 1 ────────────────────────────────────────────────────────
  // {{BEATS_FOR_SUBMODULE_1}}
  // Each beat in the mockplay yaml maps to a small block of these calls:
  //   await markBeat(page, '<beat-id>', '<submodule>');
  //   await page.goto('{route}', { waitUntil: 'networkidle' });
  //   await installHighlights(page);          // re-install on navigations
  //   await focusOn(page, locator, { holdMs: ... });
  //   await clearFocus(page);
  //   await moveAndClick(page, locator);
  //   await smoothScroll(page, 280);
  //   await typeSlow(page, locator, 'text');
  //   await beat(page, ms);

  expect(true).toBe(true);
});
